GET http://127.0.0.1:8000/menu-item/ HTTP/1.1

###

GET http://127.0.0.1:8000/menu-item/6 HTTP/1.1

###
PATCH http://127.0.0.1:8000/menu-item/6 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5NzU5MTY1LCJpYXQiOjE3NTk3NTg4NjUsImp0aSI6ImM3ZGExZjJlOWQ2NzQ0MDliOTNiZDEyZGFmNWZlNjkyIiwidXNlcl9pZCI6Mn0.JxaIn532scQ1VYui2QGseEAd1f7EeI1bEZSVlo7obA4

{
    "price": 4.80
}

###

POST http://127.0.0.1:8000/menu-item/ HTTP/1.1
Content-Type: application/json

{
    "item_name": "Garlic soup",
    "category": "Soup",
    "price": 4.50,
    "description": "Delicious soup"
}

###
POST http://127.0.0.1:8000/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "rest_admin",
    "password": "hesloadmin1"
}

###
GET http://127.0.0.1:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyMDA2NTg4LCJpYXQiOjE3NjIwMDYyODgsImp0aSI6IjM1OGM3YTBlZDMzODQ2ZTg4NmVjMTRiNzEyMDFiZTlmIiwidXNlcl9pZCI6MX0.G9T-u_UanP0gJ-KrmavpP1_o3UuQQ25BOepzTNSrpi4


###
POST http://127.0.0.1:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyMTczOTY2LCJpYXQiOjE3NjIxNzM2NjYsImp0aSI6ImI5OTcxZGM1ODA2NzQ0YzA4ZjZhNzg3NmMxNzE1NTNiIiwidXNlcl9pZCI6MX0.YXpksTE3YzjkTHjgCtyL9PT76sk6pVdF7NspTNXUSxk

{
    "status": "pending",
    "user": 1,
    "delivery_crew": 2,
    "items": [
        {
            "menuitem": 6,
            "quantity": 4
        }
    ]
}

###
GET http://127.0.0.1:8000/auth/users/me/ HTTP/1.1
Authorization: Token d83ddcfd0f22f245b15540834ecfae85982e146f


###
POST http://127.0.0.1:8000/auth/token/login HTTP/1.1
Content-Type: application/json

{
    "username": "rest_admin",
    "password": "hesloadmin1"
}

###
POST http://127.0.0.1:8000/auth/token/logout HTTP/1.1
Authorization: Token d83ddcfd0f22f245b15540834ecfae85982e146f

###
POST http://127.0.0.1:8000/auth/jwt/create HTTP/1.1
Content-Type: application/json

{
    "username": "rest_admin",
    "password": "hesloadmin1"
}

###
GET http://127.0.0.1:8000/auth/users/me/ HTTP/1.1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyMzQ4MzE2LCJpYXQiOjE3NjIzNDgwMTYsImp0aSI6IjJjNjVhMzMyYzQ2YTQ3YjU5ZjI0NzA0ZTU5ODM3MjJlIiwidXNlcl9pZCI6MX0.AphP28trV85v7WExulcIY1hYuGRClrghzN0Bi1c5hpA
